# Generated by Django 4.1.4 on 2023-01-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
