# Generated by Django 4.1.4 on 2023-02-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_addtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddstudentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=25)),
                ('b_name', models.CharField(max_length=50)),
            ],
        ),
    ]
