# Generated by Django 4.1.4 on 2023-02-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_addstudentbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='course_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
