# Generated by Django 4.1.4 on 2023-01-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='course/')),
            ],
        ),
    ]
