# Generated by Django 4.1.4 on 2023-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techadmin', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
            ],
        ),
    ]
